events {}

http {
    # SSL 공통 설정 (보안 강화)
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;

    # 1. HTTP -> HTTPS 리다이렉트
    server {
        listen 80;
        server_name A.zaehyeong.cloud B.zaehyeong.cloud;
        return 301 https://$host$request_uri;
    }

    # TODO: A 서비스
    server {
        listen 443 ssl;
        server_name A.zaehyeong.cloud;

        ssl_certificate /etc/nginx/certs/fullchain.pem; # 인증서 경로
        ssl_certificate_key /etc/nginx/certs/privkey.pem; # 키 경로

        location / {
            proxy_pass http://service_a:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme; # HTTPS 프로토콜 정보 전달
        }
    }

    # TODO: B 서비스
    server {
        listen 443 ssl;
        server_name B.zaehyeong.cloud;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location / {
            proxy_pass http://service_b:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}